/*
UPDATE BILLING_DOC SET ACCOUNT_ID = (SELECT ACCOUNT_ID FROM ACCOUNT WHERE CUSTOMER_ID = 553);

DELETE FROM ACCOUNT WHERE CUSTOMER_ID <> 553;

DELETE FROM CUSTOMER_ADDRESS WHERE (CUSTOMER_ID <> 553);
DELETE FROM CUSTOMER_NAME WHERE (CUSTOMER_ID <> 553);
DELETE FROM CUSTOMER WHERE (CUSTOMER_ID <> 553);

UPDATE BILLING_DOC SET DOCUMENT_TYPE = 2, RECEIPT_TYPE = 1 WHERE DOCUMENT_TYPE = 1 AND DOCUMENT_DATE <= '2005-08-31 23:23:23';


DELETE FROM DO_ITEM WHERE CREATE_BY = 8084;
DELETE FROM BILLING_DOC WHERE CREATE_BY = 8084;

   Manually change the corresponse DO to the actual customer.
*/
