DELETE FROM MOVEMENT_ITEM;
DELETE FROM CAPITAL_MOVEMENT;
DELETE FROM IMPORT_ITEM;
DELETE FROM EXPORT_ITEM;
DELETE FROM DO_ITEM;
DELETE FROM RECEIPT_ITEM;
DELETE FROM RO_ITEM;
DELETE FROM CASH_TRAN;
DELETE FROM RECEIPT_CNDN;
DELETE FROM BILLING_DOC;
DELETE FROM CASH_DOC;
DELETE FROM INVENTORY_DOC;
DELETE FROM BALANCE_ACCUM;

DELETE FROM EXPENSE_RATIO;
DELETE FROM REVENUE_COST_ITEM;
DELETE FROM REVENUE_COST;
