
CREATE TABLE DOCUMENT_TYPE
(
   DOCUMENT_TYPE_ID      ID_TYPE NOT NULL,
   DOCUMENT_TYPE_NO      CODE_TYPE NOT NULL,
   DOCUMENT_TYPE_NAME    CODE_TYPE NOT NULL,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
