CREATE TABLE EXPTYPE_RATIO
(
   EXPTYPE_RATIO_ID      ID_TYPE NOT NULL,
   EXPENSE_TYPE_ID       ID_TYPE NOT NULL,
   LOCATION_ID           ID_TYPE NOT NULL,
   RATIO                 MONEY_TYPE,
   RATIO_AMOUNT          MONEY_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
