CREATE TABLE MOVEMENT_ITEM
(
   MOVEMENT_ITEM_ID      ID_TYPE NOT NULL,
   CAPITAL_MOVEMENT_ID   ID_TYPE NOT NULL,
   EXPENSE_TYPE          ID_TYPE,
   PART_ITEM_ID          ID_TYPE,
   CAPITAL_AMOUNT        MONEY_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
