CREATE TABLE RO_ITEM
(
   RO_ITEM_ID            ID_TYPE NOT NULL,
   BILLING_DOC_ID        ID_TYPE NOT NULL,
   EXPENSE_TYPE          ID_TYPE,
   PART_ITEM_ID          ID_TYPE,
   LOCATION_ID           ID_TYPE,
   ITEM_AMOUNT           MONEY_TYPE,
   TOTAL_WEIGHT          MONEY_TYPE,
   AVG_WEIGHT            MONEY_TYPE,
   TOTAL_PRICE           MONEY_TYPE,
   AVG_PRICE             MONEY_TYPE,
   GUI_ID                ID_TYPE,
   PIG_STATUS            ID_TYPE,
   LINK_ID               ID_TYPE,
   EXPENSE_DESC          DESC_TYPE,
   TRANSACTION_SEQ       ID_TYPE,

   CREATE_DATE           DATE_TYPE NOT NULL,
   CREATE_BY             ID_TYPE NOT NULL,
   MODIFY_DATE           DATE_TYPE NOT NULL,
   MODIFY_BY             ID_TYPE NOT NULL
);
