ALTER TABLE BALANCE_ACCUM ADD CONSTRAINT BALANCE_ACCUM_ID_PK PRIMARY KEY (BALANCE_ACCUM_ID);
ALTER TABLE BALANCE_ACCUM ADD CONSTRAINT BALANCE_ACCUM_PART_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
ALTER TABLE BALANCE_ACCUM ADD CONSTRAINT BALANCE_ACCUM_LOCATION_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;

