
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_ID_PK PRIMARY KEY (CAPITAL_MOVEMENT_ID);
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_IVD_FK1 FOREIGN KEY (IVD_ID) REFERENCES INVENTORY_DOC;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_BLD_FK1 FOREIGN KEY (BL_ID) REFERENCES BILLING_DOC;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_HOUSE_FK1 FOREIGN KEY (FROM_HOUSE_ID) REFERENCES LOCATION;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_HOUSE_FK2 FOREIGN KEY (TO_HOUSE_ID) REFERENCES LOCATION;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_STATUS_FK1 FOREIGN KEY (PIG_STATUS) REFERENCES PRODUCT_STATUS;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_IMP_FK1 FOREIGN KEY (IMPORT_ITEM_ID) REFERENCES IMPORT_ITEM;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_EXP_FK1 FOREIGN KEY (EXPORT_ITEM_ID) REFERENCES EXPORT_ITEM;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_PIG_FK1 FOREIGN KEY (PIG_ID) REFERENCES PART_ITEM;
ALTER TABLE CAPITAL_MOVEMENT ADD CONSTRAINT CAPITAL_MOVEMENT_DOC_ID_FK1 FOREIGN KEY (BILLING_DOC_ID) REFERENCES BILLING_DOC;
