ALTER TABLE EXPENSE_RATIO ADD CONSTRAINT EXPENSE_RATIO_ID_PK PRIMARY KEY (EXPENSE_RATIO_ID);
ALTER TABLE EXPENSE_RATIO ADD CONSTRAINT EXPENSE_RATIO_HOUSE_ID_FK FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION;
ALTER TABLE EXPENSE_RATIO ADD CONSTRAINT EXPENSE_RATIO_EXPENSE_ID_FK FOREIGN KEY (EXPENSE_TYPE_ID) REFERENCES EXPENSE_TYPE;
