
ALTER TABLE PRTITEM_MAP ADD CONSTRAINT PRTITEM_MAP_ID_PK PRIMARY KEY (PRTITEM_MAP_ID);
ALTER TABLE PRTITEM_MAP ADD CONSTRAINT PRTITEM_MAP_WEEK_ID_FK FOREIGN KEY (YEAR_WEEK_ID) REFERENCES YEAR_WEEK;
ALTER TABLE PRTITEM_MAP ADD CONSTRAINT PRTITEM_MAP_PRODUCT_TYPE_ID_FK FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE;
ALTER TABLE PRTITEM_MAP ADD CONSTRAINT PRTITEM_MAP_PRODUCT_TYPE_ID_FK FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE;
