
ALTER TABLE MOVEMENT_ITEM ADD CONSTRAINT MOVEMENT_ITEM_ID_PK PRIMARY KEY (MOVEMENT_ITEM_ID);
ALTER TABLE MOVEMENT_ITEM ADD CONSTRAINT MOVEMENT_ITEM_CPM_ID_FK FOREIGN KEY (CAPITAL_MOVEMENT_ID) REFERENCES CAPITAL_MOVEMENT;
ALTER TABLE MOVEMENT_ITEM ADD CONSTRAINT MOVEMENT_ITEM_EXPENSE_ID_FK FOREIGN KEY (EXPENSE_TYPE) REFERENCES EXPENSE_TYPE;
ALTER TABLE MOVEMENT_ITEM ADD CONSTRAINT MOVEMENT_ITEM_PRTITM_ID_FK FOREIGN KEY (PART_ITEM_ID) REFERENCES PART_ITEM;
