ALTER TABLE RO_ITEM ADD CONSTRAINT RO_ITEM_ID_PK PRIMARY KEY (RO_ITEM_ID);
ALTER TABLE RO_ITEM ADD CONSTRAINT RO_ITEM_RO_ID_FK FOREIGN KEY (BILLING_DOC_ID) REFERENCES BILLING_DOC;
ALTER TABLE RO_ITEM ADD CONSTRAINT RO_ITEM_PIG_STATUS_ID_FK FOREIGN KEY (PIG_STATUS) REFERENCES PRODUCT_STATUS;
